# Generated by Django 3.2.13 on 2022-09-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220903_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
